import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// making navbar
import Nav from "@/Components/NavBar/Nav";
import Footer from "@/Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NepaTronix",
  description: "Generated by create next app",  icons: {
    icon: "/mainImages/logo2.png", // Add your logo here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
